# Generated by Django 2.1.7 on 2021-06-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotnews',
            name='priority',
            field=models.IntegerField(choices=[(1, '第一级'), (2, '第二级'), (3, '第三级')], help_text='优先级', verbose_name='优先级'),
        ),
    ]
